Repository scilus/scilpy, pull requests merged in 2023-11, with the labels that each got.

#799 Move bvec_bval_tool from utils to gradients module
  scilpy/dwi/__init__.py
  scilpy/dwi/utils.py
  scilpy/gradients/bvec_bval_tools.py
  scilpy/image/volume_operations.py
  scilpy/io/utils.py
  scilpy/reconst/b_tensor_utils.py
  scilpy/reconst/frf.py
  scilpy/reconst/raw_signal.py
  scripts/scil_compute_NODDI.py
  scripts/scil_compute_dti_metrics.py
  scripts/scil_compute_freewater.py
  scripts/scil_compute_kurtosis_metrics.py
  scripts/scil_compute_memsmt_frf.py
  scripts/scil_compute_msmt_fodf.py
  scripts/scil_compute_msmt_frf.py
  scripts/scil_compute_powder_average.py
  scripts/scil_compute_qball_metrics.py
  scripts/scil_compute_sf_from_sh.py
  scripts/scil_compute_ssst_fodf.py
  scripts/scil_convert_gradients_fsl_to_mrtrix.py
  scripts/scil_convert_gradients_mrtrix_to_fsl.py
  scripts/scil_detect_dwi_volume_outliers.py
  scripts/scil_extract_b0.py
  scripts/scil_extract_dwi_shell.py
  scripts/scil_flip_gradients.py
  scripts/scil_resample_bvals.py
  scripts/scil_run_commit.py
  scripts/scil_screenshot_dti.py
  scripts/scil_swap_gradient_axis.py
  scripts/scil_visualize_gradients.py
Labels: restructuration

#778 Add test volume_math
  scilpy/image/tests/test_volume_math.py
  scilpy/image/volume_math.py
  scilpy/io/fetcher.py
Labels: restructuration

#801 scil_convert_fdf.py
  scilpy/io/varian_fdf.py
  scripts/scil_convert_fdf.py
Labels: restructuration

#803 scil_merge_json move function into module
  scilpy/tests/dict.py
  scilpy/tractanalysis/json_utils.py
  scilpy/tractanalysis/tests/test_json_utils.py
  scripts/scil_merge_json.py
Labels: restructuration

#795 adding vtk legacy options to scil_convert_surface script
  requirements.txt
  scilpy/gradients/tests/test_gradients_utils.py
  scilpy/io/fetcher.py
  scilpy/surfaces/tests/test_surfaces_utils.py
  scilpy/surfaces/utils.py
  scilpy/tests/arrays.py
  scripts/scil_convert_surface.py
  scripts/tests/test_convert_surface.py
Labels: WIP

#774 FIX/ENH: Streamline (and mask) operations refactor
  scilpy/io/fetcher.py
  scilpy/tractanalysis/scoring.py
  scilpy/tractograms/streamline_and_mask_operations.py
  scilpy/tractograms/streamline_operations.py
  scilpy/tractograms/tests/test_streamline_and_mask_operations.py
  scilpy/tractograms/tests/test_streamline_operations.py
  scilpy/tractograms/tests/test_tractogram_operations.py
  scilpy/tractograms/tests/tests_streamline_and_mask_operations.py
  scilpy/tractograms/tests/tests_streamline_operations.py
  scilpy/utils/streamlines.py
  scripts/scil_compute_endpoints_map.py
  scripts/scil_cut_streamlines.py
  scripts/scil_decompose_connectivity.py
  scripts/scil_evaluate_bundles_individual_measures.py
  scripts/scil_evaluate_bundles_pairwise_agreement_measures.py
Labels: bug, enhancement, restructuration

#802 Final check main of script 1) dwi 2) gradient
  scilpy/dwi/utils.py
  scilpy/gradients/bvec_bval_tools.py
  scilpy/gradients/tests/test_bvec_bval_tools.py
  scilpy/io/gradients.py
  scilpy/io/varian_fdf.py
  scilpy/utils/util.py
  scripts/legacy/scil_flip_gradients.py
  scripts/legacy/scil_resample_bvals.py
  scripts/legacy/scil_swap_gradients.py
  scripts/scil_apply_bias_field_on_dwi.py
  scripts/scil_extract_dwi_shell.py
  scripts/scil_flip_gradients.py
  scripts/scil_generate_gradient_sampling.py
  scripts/scil_gradients_modify_axes.py
  scripts/scil_gradients_round_bvals.py
  scripts/scil_resample_bvals.py
  scripts/scil_split_dwi.py
  scripts/scil_swap_gradient_axis.py
  scripts/scil_validate_and_correct_bvecs.py
  scripts/tests/test_gradients_modify_axes.py
  scripts/tests/test_gradients_round_bvals.py
  scripts/tests/test_resample_bvals.py
  scripts/tests/test_split_dwi.py
  scripts/tests/test_swap_gradient_axis.py
Labels: restructuration

#750 ENH: Add Parallel Transport Tractography to `scil_compute_local_tracking`
  scilpy/tracking/tools.py
  scilpy/tracking/utils.py
  scripts/scil_compute_local_tracking.py
  scripts/tests/test_compute_local_tracking.py
Labels: enhancement

#806 Cleaning reconst module
  docs/source/modules/scilpy.reconst.rst
  scilpy/dwi/operations.py
  scilpy/dwi/utils.py
  scilpy/io/b_tensor.py
  scilpy/io/tensor.py
  scilpy/reconst/divide.py
  scilpy/reconst/dwi.py
  scilpy/reconst/fodf.py
  scilpy/reconst/multi_processes.py
  scilpy/reconst/sh.py
  scilpy/reconst/tests/test_aodf.py
  scilpy/reconst/tests/test_bingham.py
  scilpy/reconst/tests/test_divide.py
  scilpy/reconst/tests/test_dwi.py
  scilpy/reconst/tests/test_fiber_coherence.py
  scilpy/reconst/tests/test_fodf.py
  scilpy/reconst/tests/test_frf.py
  scilpy/reconst/tests/test_mti.py
  scilpy/reconst/tests/test_sh.py
  scilpy/reconst/tests/test_utils.py
  scilpy/tractanalysis/afd_along_streamlines.py
  scilpy/tractanalysis/lobe_metrics_along_streamlines.py
  scripts/legacy/scil_flip_gradients.py
  scripts/legacy/scil_resample_bvals.py
  scripts/legacy/scil_swap_gradients.py
  scripts/scil_apply_bias_field_on_dwi.py
  scripts/scil_compute_asym_odf_metrics.py
  scripts/scil_compute_divide.py
  scripts/scil_compute_dti_metrics.py
  scripts/scil_compute_fodf_metrics.py
  scripts/scil_compute_mean_fixel_afd_from_bundles.py
  scripts/scil_compute_mean_fixel_afd_from_hdf5.py
  scripts/scil_compute_mean_fixel_lobe_metric_from_bundles.py
  scripts/scil_compute_memsmt_fodf.py
  scripts/scil_compute_memsmt_frf.py
  scripts/scil_compute_msmt_fodf.py
  scripts/scil_compute_sf_from_sh.py
  scripts/scil_compute_sh_from_signal.py
  scripts/scil_compute_ssst_fodf.py
  scripts/scil_convert_sh_basis.py
  scripts/scil_convert_tensors.py
  scripts/scil_gradients_modify_axes.py
Labels: restructuration

#787 Move valid inputs from reorder_philips into module gradients
  scilpy/gradients/tests/test_gradients_utils.py
  scilpy/gradients/utils.py
  scripts/scil_reorder_dwi_philips.py
Labels: restructuration

#815 RF - Tracking/Tractogram Scripts
  docs/source/documentation/tractogram_registration.rst
  scripts/legacy/scil_add_tracking_mask_to_pft_maps.py
  scripts/legacy/scil_apply_transform_to_tractogram.py
  scripts/legacy/scil_compute_local_tracking.py
  scripts/legacy/scil_compute_local_tracking_dev.py
  scripts/legacy/scil_compute_maps_for_particle_filter_tracking.py
  scripts/legacy/scil_compute_pft.py
  scripts/legacy/scil_filter_tractogram.py
  scripts/legacy/scil_flip_gradients.py
  scripts/legacy/scil_flip_streamlines.py
  scripts/legacy/scil_register_tractogram.py
  scripts/legacy/scil_resample_bvals.py
  scripts/legacy/scil_resample_tractogram.py
  scripts/legacy/scil_shuffle_streamlines.py
  scripts/legacy/scil_split_tractogram.py
  scripts/legacy/scil_swap_gradients.py
  scripts/scil_tracking_local.py
  scripts/scil_tracking_local_dev.py
  scripts/scil_tracking_pft.py
  scripts/scil_tracking_pft_maps.py
  scripts/scil_tracking_pft_maps_edit.py
  scripts/scil_tractogram_apply_transform.py
  scripts/scil_tractogram_filter.py
  scripts/scil_tractogram_flip.py
  scripts/scil_tractogram_register.py
  scripts/scil_tractogram_resample.py
  scripts/scil_tractogram_shuffle.py
  scripts/scil_tractogram_split.py
  scripts/tests/test_tracking_local.py
  scripts/tests/test_tracking_local_dev.py
  scripts/tests/test_tracking_pft.py
  scripts/tests/test_tracking_pft_maps.py
  scripts/tests/test_tracking_pft_maps_edit.py
  scripts/tests/test_tractogram_apply_transform.py
  scripts/tests/test_tractogram_filter.py
  scripts/tests/test_tractogram_flip.py
  scripts/tests/test_tractogram_register.py
  scripts/tests/test_tractogram_resample.py
  scripts/tests/test_tractogram_split.py
Labels: restructuration
