Repository scilus/scilpy, pull requests merged in 2024-02, with the labels that each got.

#894 FIX: scil_visualize_connectivity text rotation
  scripts/scil_visualize_connectivity.py
Labels: bug

#810 Scripts to project 3D and 4D maps to streamline points and perform math operations in space of streamline points
  .python-version
  scilpy/tractograms/dps_and_dpp_management.py
  scilpy/tractograms/streamline_operations.py
  scilpy/tractograms/tests/test_dps_and_dpp_management.py
  scripts/scil_tractogram_dpp_math.py
  scripts/scil_tractogram_project_map_to_streamlines.py
  scripts/tests/test_tractogram_dpp_math.py
  scripts/tests/test_tractogram_project_map_to_streamlines.py
Labels: WIP

#734 Working synb0 wrapper in scilpy
  data/mni_icbm152_t1_tal_nlin_asym_09c_masked_2_5.nii.gz
  scilpy/image/volume_operations.py
  scilpy/io/fetcher.py
  scilpy/preprocessing/distortion_correction.py
  scilpy/tractanalysis/afd_along_streamlines.py
  scripts/scil_dwi_prepare_topup_command.py
  scripts/scil_volume_b0_synthesis.py
  scripts/tests/test_volume_b0_synthesis.py
Labels: enhancement

#920 FIX: screenshot functions no longer working
  scilpy/viz/scene_utils.py
  scripts/tests/test_screenshot_volume.py
Labels: bug
